### ISSUE TITLE
✨ feat: 동아리, 갤러리 API 개발

### ISSUE THREAD

**Issue by Ohwooseok** [SMUNION/SMUNION-BE#6]
# Title

- 동아리 관련 API 기능 개발하겠습니다.

# TODO

- [x] 동아리 생성
- [x] 동아리 수정 
- [x] 동아리 부서 생성
- [x] 동아리 부서 전체 조회
- [x] 부서 삭제
- [x] 갤러리 생성
- [x] 갤러리 수정
- [x] 갤러리 조회
- [x] 갤러리 삭제
- [x] 갤러리 전체 조회

# etc

- 참고자료 등 기타 내용 작성
